# This program uses the preprocess fucntion, and plots the fourth requried plot.

source("preprocess.R")
subdf<- preprocess()
png(filename = "plot4.png", width = 480, height = 480)
old.par <- par(mfrow=c(2,2))
plot(x=(subdf$DateTime),y=subdf$Global_active_power,type="l",ylab="Global Active Power (kilowatts)",xlab="")
plot(x=(subdf$DateTime),y=subdf$Voltage,type="l",ylab="Voltage",xlab="datetime")
plot(x= subdf$DateTime, y= subdf$Sub_metering_1, type = "l", xlab = "", ylab = "Energy Sub metering")
lines(x= subdf$DateTime, y= subdf$Sub_metering_2, col= "RED")
lines(x= subdf$DateTime, y= subdf$Sub_metering_3, col= "BLUE")
#legend("topright",c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty = c(2,2,2),lwd = c(1.5,1.5,1.5),col = c("black","red","blue"),cex=0.5, pt.cex = 1.5)
legend("topright",c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),bty="l",col=c("black","red","blue"),lwd=2,cex=0.25)
plot(x=(subdf$DateTime),y=subdf$Global_reactive_power,type="l",ylab="Global Reactive Power (kilowatts)",xlab="")
dev.off()
